server:
  host: "0.0.0.0"
  port: 6379
  max_connections: 10000
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"
  
cache:
  max_memory: "1GB"
  eviction_policy: "lru"  # lru, lfu, random
  cleanup_interval: "60s"
  
cluster:
  enabled: false
  nodes: []
  replica_count: 1
  virtual_nodes: 150
  
metrics:
  enabled: true
  port: 8080
  path: "/metrics"
  
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, console
  output: "stdout"  # stdout, stderr, file
  file: "/var/log/hpcs/hpcs.log"